### ISSUE TITLE
Your Usage is Wrong？

### ISSUE THREAD

**Issue by tangj1206** [michaelzoidl/swap-array#1]
// Your Usage 
import SwapArray from 'swap-array';

var SomeArray = ['thats','cool','dude'];

SwapArray(SomeArray, 0, 2);
// ['dude','thats','cool'];    -------->  **expect ['dude','cool','thats']** ???

**Comment by michaelzoidl** [comment]
Oh, you're right.. 👍 
But it's just in the README, so the module works well.. :)

Thank you anyway, i will update this tonight
